- name: download miniconda3
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/install-miniconda.sh
    mode: 0550

- name: create directory for instalation
  file:
    path: ~/.miniconda3
    state: directory
    mode: 755
    recurse: yes

- name: install miniconda3
  shell: /tmp/install-miniconda.sh -b -u -p /opt/miniconda3

- name: remove miniconda3 installer
  file:
    state: absent
    path: /tmp/install-miniconda.sh

- name: add miniconda to PATH
  become: True
  shell: echo 'export PATH=~/.miniconda3/bin:$PATH' >> ~/.bashrc
